### ISSUE TITLE
Request for Contribution

### ISSUE THREAD

**Issue by frudolph77** [alexander-zibert/turing-machine-board-game-solver#1]
Hey Alexander,

do you accept pull requests for this project?. 

I've made some changes to the UI:
- replaced your Check Button with an Icon. The small icon is a Folder with a check mark and a X on it. Color `primary.dark`
-  change the Icons on the RoundCard.  I'd like to have them red and green, but the original icons didn't look nice then. So i change the check mark and the x and also the empty box is now an icon instead of an div with a border. I just looks better then. Colors: `primary.dark`, `secondary.dark`
- removed some white space on the RoundCard to have it more compact

Add some features:
- added a very simple, not yet complete, language switch. Needs to be changed to a dropdown, persistence  need's to be changed.
- add the possibility to download/upload the state Clipboard with corresponding icons , not yet started. Just something I've in mind, due to the fact that I used to different  devices to log my plays.

Kind Regards Frank

![grafik](https://github.com/alexander-zibert/turing-machine-board-game-solver/assets/63302676/6eff5790-814d-4cfb-a74d-b94c8d8c6ecb)

**Comment by alexander-zibert** [comment]
Hey Frank,

the changes look great. Feel free to create the pull request.

Importing/Exporting the state from the Clipboard should be quite easy. The whole app state is already persisted in LocalStorage.

**Comment by frudolph77** [comment]
I'm done with the UI changes, more or less. There is a change in the layout of the criteria cards that is completely up to my preference.

I don't like the layout of the criteria cards in an extreme game.
``` 
A  B      but         A  A
A  B      ------>     B  B
C  D      i like      C  C 
C  D                  D  D
``` 
So I've changed `Comments.tsx` and `Comment.tsx. Where the layout is much simpler and less cluttered now.



I currently stopped working on import/export. Due to the fact that the persistence layer has some flaws.
The game hash in `saves` the is the primary key, therefore it's not possible to play a game twice, without overwriting the state of the previous play. And it's also not multi user capable, so an other 'user' will overwrite the state too.

**Comment by alexander-zibert** [comment]
@frudolph77 I mostly play on standard or nightmare mode. If this feels better for you, and cleans up the code, this seems like a good change.

**Comment by frudolph77** [comment]
I will create a PR later this weekend, and you can take a look a the code.
