### ISSUE TITLE
Check the answer

### ISSUE THREAD

**Issue by cpasoft** [alexander-zibert/turing-machine-board-game-solver#10]
The application has a method to check if all the premises are correct. However, it does not check if the final answer is correct.
Let's take the example #B51A659...
For this example, the application returns that the premises are all correct for both result 344 and result 244:
![imagen](https://github.com/alexander-zibert/turing-machine-board-game-solver/assets/29692062/e7278abd-c377-49e2-b4a5-f840bdc34fd8)
![imagen](https://github.com/alexander-zibert/turing-machine-board-game-solver/assets/29692062/1df0c8ff-6d7b-46ae-84d9-be05b93a22dc)

In addition, if you cross out all the numbers in the blue triangle, it also returns "all deductions are valid".
![imagen](https://github.com/alexander-zibert/turing-machine-board-game-solver/assets/29692062/6d284523-6ff5-4ba3-b55f-9d5aa1f02a17)

I think the right thing to do would be to check it with the result given by the turingmachine website, but I don't know if this is even possible.

By the way, wouldn't it be possible for the application to remember the name of one game to another?
![imagen](https://github.com/alexander-zibert/turing-machine-board-game-solver/assets/29692062/601a2171-1ef5-4c65-82c8-db6635a5633d)

**Comment by alexander-zibert** [comment]
This is indeed a bug, and it seems to occur specifically when an invalid query is marked on the left side. In the second query, the verifier "A" should display a checkmark instead of a cross.

Behind the scenes, the app deduces that no valid code is possible with these queries, leading to a disruption in the deduction checks.

To address this issue, I am planning to improve the alert. If the app determines that no valid code is possible based on the provided queries, a warning will be displayed to alert the user.

**Comment by frudolph77** [comment]
To remember the user name shouldn't be that difficult, I'll take look.

**Comment by alexander-zibert** [comment]
I refactored the frontend of the deduction check a bit.

The following three messages would be available with the next update:

1)

![image](https://github.com/alexander-zibert/turing-machine-board-game-solver/assets/3660540/8c4bb1da-8047-481c-8763-62ba3faf9fc9)

2) 

![image](https://github.com/alexander-zibert/turing-machine-board-game-solver/assets/3660540/3fa747f9-442b-4252-86f6-efc35c3569d5)

3) 

![image](https://github.com/alexander-zibert/turing-machine-board-game-solver/assets/3660540/e4f13a9d-91bb-4dfb-b0c5-ac593918b413)

Are the messages clear?

**Comment by cpasoft** [comment]
I think it is quite clear...

**Comment by frudolph77** [comment]
It seems there is a bug in the deduction. 251 is the solution for #B65 FWE R 
![grafik](https://github.com/alexander-zibert/turing-machine-board-game-solver/assets/63302676/67fb2e47-5b6f-4a83-862d-86d613de131b)

**Comment by alexander-zibert** [comment]
@frudolph77 I think it is not a bug. With this setup, in the third query with the code 531 the verifier F should give false as answer, because 531 is descending and the machine tests for no order.

**Comment by frudolph77** [comment]
@alexander-zibert oh, damm your'e right, that was an incorrect transfer from paper into the app.
