### ISSUE TITLE
Display the Number and Color/Symbol of the Verification Cards.

### ISSUE THREAD

**Issue by frudolph77** [alexander-zibert/turing-machine-board-game-solver#16]
Just hacked around. what do you think:

![grafik](https://github.com/alexander-zibert/turing-machine-board-game-solver/assets/63302676/326feb06-de2b-435a-8576-0bf9afa677e2)
The screenshot is a fake to show all possible symbols/colors. Matching Symbol for the game id is `/` 

I decided to make the Verification Card number smaller, than the Verifier, so that it is not to dominate. And also to use black as text color, because of the very bad contrast of white on yellow. The symbols are just `'◊', '#', '/', '¤'` for the moment, and not the graphic from turingmachine.info, which needs to be recreated as svg and in black color.

Just as a side note be careful when requesting games, I think they have implemented some kind of rate limit. When requesting to much games in a short time they return an error. It seems more that they have protected the API against calls from external hosts. Or all query parameters are required now.

**Comment by alexander-zibert** [comment]
This looks really great and would also help for the offline generation of puzzles mentioned in #11.
