### ISSUE TITLE
Question, maybe a bit silly

### ISSUE THREAD

**Issue by cpasoft** [alexander-zibert/turing-machine-board-game-solver#8]
First of all, I am very new to node and react. 
I have been able to run the application on PC locally, and from the mobile or tablet I can attack the URL created from the PC. 
My question is, is there a way to "compile" the application and run it exclusively on the mobile or tablet without using more resources?
If so, how do I go about it? 

Thanks in advance...

**Comment by cpasoft** [comment]
Let me explain my theory. 
You publish it here, on github, and you need the services of github for the application to work... Am I on the right track? 
Actually, the local installation done from Chrome is nothing more than a kind of bookmark that includes the basics of Chrome to navigate this application, but in reality the application is run remotely (on github in this case), so if there's no internet, it won't even show the application and will give a connection error. 
Am I really lost?

**Comment by alexander-zibert** [comment]
I'm not quite sure what you mean. You can access a hosted version of the website under https://alexander-zibert.github.io/turing-machine-board-game-solver/ .
For the hosted version you do not need to use node/react. Only if you want to help adding features or fixing bugs you need to "compile" the website locally.

An offline mode is not implemented, yet.

**Comment by cpasoft** [comment]
Don't worry, I've already done it...

I made a fork of your tree and managed to publish the changes. Now I'll try to see if there are any bugs.

Thanks for everything Alexader
