### ISSUE TITLE
Add a list of viable number combinations

### ISSUE THREAD

**Issue by cpasoft** [alexander-zibert/turing-machine-board-game-solver#9]
In the Zyle87 application, clicking twice selects the number with a circle.
It doesn't work in this fork. I don't know if this is intentional or a bug.
![imagen](https://github.com/alexander-zibert/turing-machine-board-game-solver/assets/29692062/5a741c68-aba5-4a7b-9acc-5e96e6a00d13)

**Comment by cpasoft** [comment]
I have posted some suggestions here. 
https://boardgamegeek.com/thread/3057197/article/43365737#43365737
Some of them are already implemented in this fork, but others could be very useful...

**Comment by alexander-zibert** [comment]
@cpasoft this is intentional. In my games I mostly can deduce which digits are not possible before reaching conclusions about which digit is correct. And double clicking the digit to mark it as excluded really bothered me while playing.

**Comment by frudolph77** [comment]
I don't need this circle either, I'll strike out all numbers that are not possible.

**Comment by cpasoft** [comment]
Yes, indeed, it makes perfect sense. 
On the other hand, what do you think about the suggestion to incorporate a table with the combinations of possible numbers that have not been crossed out?.
I've been using this kind of alternative notesheet for a while, and having the table really helps me figure things out.
![imagen](https://github.com/alexander-zibert/turing-machine-board-game-solver/assets/29692062/be23f653-4fdb-4c88-8fd4-fc42598a9e07)

**Comment by frudolph77** [comment]
I've seen this kind out sheets on BGG. I personally have no need for them. 

I normally use a 10.3 " tablet to note my plays. On this display you have only limited space, and then you have to scroll a lot.

But creating such a component should be relatively easy. It's only my limited amount of time, in the next weeks.
I would suggest to remove impossible numbers from that list, so that it gets smaller and smaller.

**Comment by cpasoft** [comment]
> I would suggest to remove impossible numbers from that list, so that it gets smaller and smaller.
Yes, exactly. That would be the idea.
The 125 combinations would appear at the beginning and then the ones that don't work would disappear as you cross off numbers according to your deductions.

I suggest that this table be placed at the bottom, as you will not be consulting it until the final rounds.

I think this is a great improvement.

**Comment by cpasoft** [comment]
I have renamed this issue, as the title of the original was already resolved. I leave it with the suggested list of numbers.

**Comment by alexander-zibert** [comment]
@cpasoft Would crossing off verifiers on a verifier card, also change the displayed possible combinations.

For example, if you already deduced that the verifier, verifies that the code should be three numbers in consecutive ascending order:
![image](https://github.com/alexander-zibert/turing-machine-board-game-solver/assets/3660540/9e2972ed-acc2-4061-8ddc-af3e10dee7b3)

Would the only displayed combinations in the list be:
123
234
345

**Comment by frudolph77** [comment]
That might only work for the lower numbers of the verifiers. But for verifiers with all three colors on it.
